'use strict';

angular.module('clickQuestApp')
  .value('GloveData',
{
  slot: 'glove',
  types: [
    'lightGlove',
    'mediumGlove',
    'heavyGlove'
  ],
  lightGlove: {
    bases: [
      'Hand Wrappings',
      'Fingerless Gloves',
      'Wool Gloves',
      'Silk Gloves',
      'Sorcerer Gloves'
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Humming',
      'Buzzing',
      'Shocking',
      'Electrocuting',
      'Glinting',
      'Polished',
      'Honed',
      'Gleaming',
      'Razor Sharp',
      'Serrated',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Tempest King\'s',
      'Paragon\'s',
      'Scrapper\'s',
      'Brawler\'s',
      'Gladiator\'s',
      'Hero\'s',
      'Ethereal',
      'Unworldly',
      'Empowering',
    ],
    suffixes: [
      'of the Assassin',
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Brute',
      'of the Wrestler',
      'of the Bear',
      'of the Lion',
      'of the Gorilla',
      'of the Goliath',
      'of the Leviathan',
      'of the Titan',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Stinging',
      'of Piercing',
      'of Puncturing',
      'of Penetrating',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Hydra',
      'of the Troll',
      'of the Phoenix',
      'of the Yeti',
      'of the Walrus',
      'of the Polar Bear',
      'of the Ice',
      'of the Whelpling',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Worthy',
      'of the Apt',
      'of Intercepting'
    ]
  },
  mediumGlove: {
    bases: [
      'Goathide Gloves',
      'Stealth Gloves',
      'Sturdy Gloves',
      'Wrapped Gloves',
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Humming',
      'Buzzing',
      'Shocking',
      'Electrocuting',
      'Glinting',
      'Polished',
      'Honed',
      'Gleaming',
      'Razor Sharp',
      'Serrated',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Tempest King\'s',
      'Paragon\'s',
      'Scrapper\'s',
      'Brawler\'s',
      'Gladiator\'s',
      'Hero\'s',
      'Ethereal',
      'Unworldly',
      'Empowering',
    ],
    suffixes: [
      'of the Assassin',
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Brute',
      'of the Wrestler',
      'of the Bear',
      'of the Lion',
      'of the Gorilla',
      'of the Goliath',
      'of the Leviathan',
      'of the Titan',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Stinging',
      'of Piercing',
      'of Puncturing',
      'of Penetrating',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Hydra',
      'of the Troll',
      'of the Phoenix',
      'of the Yeti',
      'of the Walrus',
      'of the Polar Bear',
      'of the Ice',
      'of the Whelpling',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Worthy',
      'of the Apt',
      'of Intercepting'
    ]
  },
  heavyGlove: {
    bases: [
      'Chainmail Gloves',
      'Iron Gloves',
      'Steelscale Gloves',
      'Reinforced Gloves',
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Humming',
      'Buzzing',
      'Shocking',
      'Electrocuting',
      'Glinting',
      'Polished',
      'Honed',
      'Gleaming',
      'Razor Sharp',
      'Serrated',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Tempest King\'s',
      'Paragon\'s',
      'Scrapper\'s',
      'Brawler\'s',
      'Gladiator\'s',
      'Hero\'s',
      'Ethereal',
      'Unworldly',
      'Empowering',
    ],
    suffixes: [
      'of the Assassin',
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Brute',
      'of the Wrestler',
      'of the Bear',
      'of the Lion',
      'of the Gorilla',
      'of the Goliath',
      'of the Leviathan',
      'of the Titan',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Stinging',
      'of Piercing',
      'of Puncturing',
      'of Penetrating',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Hydra',
      'of the Troll',
      'of the Phoenix',
      'of the Yeti',
      'of the Walrus',
      'of the Polar Bear',
      'of the Ice',
      'of the Whelpling',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Worthy',
      'of the Apt',
      'of Intercepting'
    ]
  }
});
