'use strict';

angular.module('clickQuestApp')
  .value('WeaponData',
{
  slot: 'weapon',
  types: [
    'sword',
    'gauntlet',
    'dagger',
    'spear',
    'bow',
    'axe',
    'staff'
  ],
  sword: {
    bases: [
      'Short sword',
      'Long sword',
      'Bastard sword',
      'Rapier',
      'Scimitar'
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Humming',
      'Buzzing',
      'Shocking',
      'Electrocuting',
      'Glinting',
      'Polished',
      'Honed',
      'Gleaming',
      'Razor Sharp',
      'Serrated',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Tempest King\'s',
      'Paragon\'s',
      'Scrapper\'s',
      'Brawler\'s',
      'Gladiator\'s',
      'Hero\'s',
      'Ethereal',
      'Unworldly',
      'Empowering',
    ],
    suffixes: [
      'of the Assassin',
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Brute',
      'of the Wrestler',
      'of the Bear',
      'of the Lion',
      'of the Gorilla',
      'of the Goliath',
      'of the Leviathan',
      'of the Titan',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Stinging',
      'of Piercing',
      'of Puncturing',
      'of Penetrating',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Hydra',
      'of the Troll',
      'of the Phoenix',
      'of the Yeti',
      'of the Walrus',
      'of the Polar Bear',
      'of the Ice',
      'of the Whelpling',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Worthy',
      'of the Apt',
      'of Intercepting'
    ],
    verbs: [
      'stab',
      'slash',
      'slice',
      'swipe',
      'rupture',
      'cut',
      'cleave',
      'assault'
    ]
  },
  mace: {
    bases: [
      'Mace',
      'Morning Star',
      'Flail',
      'Club',
      'Spiked Club',
      'Construction Hammer',
      'Mallet',
      'Great Hammer',
      'Maul',
      'Gavel'
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Entombing',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Blasting',
      'Sparking',
      'Electrocuting',
      'Glinting',
      'Polished',
      'Honed',
      'Gleaming',
      'Razor Sharp',
      'Jagged',
      'Serrated',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Tempest King\'s',
      'Paragon\'s',
      'Scrapper\'s',
      'Brawler\'s',
      'Gladiator\'s',
      'Hero\'s',
      'Unworldly',
      'Empowering'
    ],
    suffixes: [
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Brute',
      'of the Wrestler',
      'of the Bear',
      'of the Lion',
      'of the Gorilla',
      'of the Goliath',
      'of the Leviathan',
      'of the Titan',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Hydra',
      'of the Troll',
      'of the Phoenix',
      'of the Yeti',
      'of the Walrus',
      'of the Polar Bear',
      'of the Ice',
      'of the Whelpling',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Worthy',
      'of the Apt',
      'of Intercepting',
      'of Walling',
      'of Impact',
      'of Dazing',
      'of Stunning',
      'of Slamming',
      'of Staggering'
    ],
    verbs: [
      'bludgeon',
      'slam',
      'maim',
      'crush',
      'bluster',
      'pound'
    ]
  },
  dagger: {
    bases: [
      'Shank',
      'Stilleto',
      'Dirk',
      'Fanged Knife',
      'Butcher Knife',
      'Dagger',
      'Butter Knife'
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Entombing',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Humming',
      'Buzzing',
      'Electrocuting',
      'Glinting',
      'Polished',
      'Honed',
      'Gleaming',
      'Razor Sharp',
      'Jagged',
      'Serrated',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Agile',
      'Scrapper\'s',
      'Brawler\'s',
      'Shadowy',
      'Ethereal',
      'Unworldly'
    ],
    suffixes: [
      'of Accuracy',
      'of Precision',
      'of the Assassin',
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Lion',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Stinging',
      'of Piercing',
      'of Puncturing',
      'of Penetrating',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Phoenix',
      'of the Ice',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Crystal',
      'of the Prism',
      'of the Worthy',
      'of the Apt',
      'of Intercepting'
    ],
    verbs: [
      'stab',
      'shank',
      'gash',
      'prick',
      'pierce'
    ]
  },
  spear: {
    bases: [
      'Spear',
      'Trident',
      'Pike',
      'Long Fork',
      'Lance',
      'Harpoon'
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Entombing',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Humming',
      'Buzzing',
      'Electrocuting',
      'Glinting',
      'Polished',
      'Honed',
      'Gleaming',
      'Razor Sharp',
      'Jagged',
      'Serrated',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Agile',
      'Tempest King\'s',
      'Paragon\'s',
      'Gladiator\'s',
      'Hero\'s',
      'Unworldly',
      'Empowering'
    ],
    suffixes: [
      'of Accuracy',
      'of Precision',
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Lion',
      'of the Titan',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Stinging',
      'of Piercing',
      'of Puncturing',
      'of Penetrating',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Hydra',
      'of the Troll',
      'of the Phoenix',
      'of the Yeti',
      'of the Walrus',
      'of the Polar Bear',
      'of the Ice',
      'of the Whelpling',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Crystal',
      'of the Prism',
      'of the Worthy',
      'of the Apt'
    ],
    verbs: [
      'impale',
      'jab',
      'puncture',
      'skewer',
      'skiver'
    ]
  },
  bow: {
    bases: [
      'Short Bow',
      'Medium Bow',
      'Long Bow',
      'Recurve Bow',
      'Decurve Bow',
      'Crossbow',
      'Bolt Launcher',
      'Siege Bow',
      'Ballista',
      'Heavy Crossbow'
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Entombing',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Electrocuting',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Agile',
      'Sharpshooter\'s'
    ],
    suffixes: [
      'of Accuracy',
      'of Precision',
      'of the Sniper',
      'of the Marksman',
      'of the Deadeye',
      'of the Ranger',
      'of the Assassin',
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Lion',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Stinging',
      'of Piercing',
      'of Puncturing',
      'of Penetrating',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Phoenix',
      'of the Ice',
      'of the Whelpling',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Crystal',
      'of the Prism',
      'of the Worthy',
      'of the Apt'
    ],
    verbs: [
      'barrage',
      'shoot',
      'bombard',
      'shower',
      'broadside'
    ]
  },
  axe: {
    bases: [
      'Axe',
      'Dwarven Axe',
      'Battle Axe',
      'War Axe',
      'Great Axe'
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Humming',
      'Buzzing',
      'Shocking',
      'Electrocuting',
      'Glinting',
      'Polished',
      'Honed',
      'Gleaming',
      'Razor Sharp',
      'Serrated',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Tempest King\'s',
      'Paragon\'s',
      'Scrapper\'s',
      'Brawler\'s',
      'Gladiator\'s',
      'Hero\'s',
      'Ethereal',
      'Unworldly',
      'Empowering',
    ],
    suffixes: [
      'of the Assassin',
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Lynx',
      'of the Fox',
      'of the Falcon',
      'of the Panther',
      'of the Leopard',
      'of the Jaguar',
      'of the Phantasm',
      'of the Brute',
      'of the Wrestler',
      'of the Bear',
      'of the Lion',
      'of the Gorilla',
      'of the Goliath',
      'of the Leviathan',
      'of the Titan',
      'of Ire',
      'of Anger',
      'of Rage',
      'of Fury',
      'of Ferocity',
      'of Destruction',
      'of Stinging',
      'of Piercing',
      'of Puncturing',
      'of Penetrating',
      'of Menace',
      'of Havoc',
      'of Disaster',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Hydra',
      'of the Troll',
      'of the Phoenix',
      'of the Yeti',
      'of the Walrus',
      'of the Polar Bear',
      'of the Ice',
      'of the Whelpling',
      'of the Salamander',
      'of the Drake',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Worthy',
      'of the Apt',
      'of Intercepting'
    ],
    verbs: [
      'slash',
      'slice',
      'swipe',
      'rupture',
      'cut',
      'cleave',
      'assault'
    ]
  },
  staff: {
    bases: [
      'Wand',
      'Bone Wand',
      'Ghost Wand',
      'Topaz Wand',
      'Crystal Wand',
      'Short Staff',
      'Long Staff',
      'Medium Staff',
      'Elder Staff',
      'Youth Staff'
    ],
    prefixes: [
      'Frosted',
      'Chilled',
      'Icy',
      'Frigid',
      'Freezing',
      'Glaciated',
      'Polar',
      'Heated',
      'Smoldering',
      'Smoking',
      'Burning',
      'Flaming',
      'Scorching',
      'Incinerating',
      'Blasting',
      'Humming',
      'Buzzing',
      'Crackling',
      'Sparking',
      'Electrocuting',
      'Glinting',
      'Wicked',
      'Vicious',
      'Bloodthirsty',
      'Cruel',
      'Tyrannical',
      'Squire\'s',
      'Journeyman\'s',
      'Reaver\'s',
      'Mercenary\'s',
      'Champion\'s',
      'Conqueror\'s',
      'Emperor\'s',
      'Emperor\'s',
      'Shining',
      'Glimmering',
      'Glittering',
      'Glowing',
      'Radiating',
      'Seething',
      'Blazing',
      'Scintillating',
      'Incandescent',
      'Resplendent',
      'Agile',
      'Sharpshooter\'s',
      'Frost Weaver\'s',
      'Winterbringer\'s',
      'Flame Spinner\'s',
      'Lava Caller\'s',
      'Thunder Lord\'s',
      'Tempest King\'s',
      'Unworldly',
      'Mage\'s',
      'Sorcerer\'s',
      'Wizard\'s',
      'Catalyzing',
      'Infusing',
      'Empowering',
      'Professor\'s',
      'Occultist\'s',
      'Caster\'s',
      'Magician\'s',
      'Warlock\'s',
      'Mage\'s',
      'Archmage\'s',
      'Apprentice\'s',
      'Adept\'s',
      'Scholar\'s',
      'Occultist\'s',
      'Incanter\'s',
      'Glyphic\'s',
      'Caster\'s',
      'Magician\'s',
      'Wizard\'s',
      'Mage\'s',
      'Archmage\'s'
    ],
    suffixes: [
      'of Light',
      'of Radiance',
      'of Skill',
      'of Ease',
      'of Mastery',
      'of Grandmastery',
      'of the Clouds',
      'of the Sky',
      'of the Meteor',
      'of the Comet',
      'of the Heavens',
      'of the Infinite',
      'of the Phantasm',
      'of the Philosopher',
      'of the Sage',
      'of the Savant',
      'of Calamity',
      'of Ruin',
      'of Unmaking',
      'of Embers',
      'of Coals',
      'of Cinders',
      'of Flames',
      'of Immolation',
      'of Ashes',
      'of Sparks',
      'of Static',
      'of Voltage',
      'of Discharge',
      'of Arcing',
      'of the Newt',
      'of the Lizard',
      'of the Hydra',
      'of the Volcano',
      'of the Magma',
      'of the Cloud',
      'of Exile',
      'of the Crystal',
      'of the Prism',
      'of the Worthy',
      'of the Apt'
    ],
    verbs: [
      'freeze',
      'burn',
      'electrocute',
      'singe',
      'slow'
    ]
  }
}
);
